name: objViewer
description: A sample web application
dependencies:
  browser: any
  game_loop:
    git: https://github.com/johnmccutchan/game_loop.git
  obj:
    git: https://github.com/udhos/obj
  vector_math: any
